server.port=8080
#spring.mongodb.uri=mongodb+srv://harshil:harshil123@cluster0.7g1gh4g.mongodb.net/students

spring.application.name=MyFirstProject
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb

spring.security.user.name=Harshil
spring.security.user.password=123456